### ISSUE TITLE
[BUG] Broken with React v18.1.0+

### ISSUE THREAD

**Issue by leffot** [react-dropzone/react-dropzone#1217]
Our monorepo uses React v18.2.0 throughout. I see that react-dropzone's peerDependencies specifices `"react": ">= 16.8 || 18.0.0"`, which means that react-dropzone causes React versions greater than 18.0.0 throw invalid hook calls. E.g.:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (.../node_modules/react/cjs/react.development.js:1618:21)
    at Html (webpack-internal:///../../node_modules/next/dist/pages/_document.js:260:106)
    at processChild (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (.../node_modules/next/dist/server/render.js:969:41)
    at async doRender (.../node_modules/next/dist/server/base-server.js:915:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (.../node_modules/next/dist/server/base-server.js:1020:28)
info  - automatically enabled Fast Refresh for 1 custom loader
error - TypeError: Cannot read properties of null (reading 'useRef')
    at Object.useRef (.../node_modules/react/cjs/react.development.js:1630:21)
    at Object.LinkComponent [as render] (webpack-internal:///../../node_modules/next/dist/client/link.js:168:42)
    at ReactDOMServerRenderer.render (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (.../node_modules/next/dist/server/render.js:756:46)
    at Object.defaultGetInitialProps (.../node_modules/next/dist/server/render.js:369:51)
    at Function.getInitialProps (webpack-internal:///../../node_modules/next/dist/pages/_document.js:21:20)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:15:89)
    at Object.<anonymous> (.../node_modules/next/dist/shared/lib/utils.js:103:33) {
  page: '/'
}
```

We don't get these errors if we downgrade our monorepo to 18.0.0.

Is there a reason peerDependencies is pegged at 18.0.0? Or can it be switched to >= 16.8 to prevent these errors?

**Comment by leffot** [comment]
Yup, sorry about this. It was another package causing the issues. Closing.
