### ISSUE TITLE
[BUG] react-dropzone cannot be imported in a Node.js ESM environment

### ISSUE THREAD

**Issue by cdauth** [react-dropzone/react-dropzone#1259]
I am experimenting with React SSR in a project that uses ESM (`"type": "module"` is set in `package.json`). The project uses react-dropzone, and although it will not be part of the server-side render, the app still imports it.

Importing react-dropzone in such an environment fails with the following error:
```
import { useDropzone } from "../node_modules/react-dropzone/dist/index.js";
         ^^^^^^^^^^^
SyntaxError: Named export 'useDropzone' not found. The requested module '../node_modules/react-dropzone/dist/index.js' is a CommonJS module, which may not support all module.exports as named exports.
```

The combination of two problems leads to this error:
* react-dropzone's `package.json` specifies a `main` and `module` field. Node.js only interprets the `main` field, which leads to the CJS build. To fix this problem, an [`exports`](https://nodejs.org/api/packages.html#package-entry-points) field should be defined whose `import` property points to the ESM build.
* The ESM build (under `dist/es/index.js`) is interpreted by Node.js as a CJS file, since no `type` is set in `package.json` and the file has a `.js` extension. To fix this problem, an ESM build with `.mjs` file extensions should be provided.

To fix the problem in a backwards-incompatible way (making a major release necessary):
* Rename the files in `dist/es` from `.js` to `.mjs`
* Add an `exports` field to `package.json`: `"exports": { "import": "dist/es/index.mjs", "default": "dist/index.js" }`

To fix the problem in a backwards-compatible way:
* Create an additional (identical) ESM build using `.mjs` extensions, for example in `dist/mjs`
* Add an `exports` field to package.json`: `"exports": { ".": { "import": "dist/mjs/index.mjs", "default": "dist/index.js" }, "./*": "./*" }`

**Comment by hlehmann** [comment]
I am also having the same issue.

**Comment by stalet** [comment]
I am also having this issue!

**Comment by jacobclarke92** [comment]
Yep this is going to continue being an issue with the prevalence of Next.  
I don't think you should have to rename to .mjs, you should be able to just specify different export types in package.json  
Something like this should do the trick:  
```json package.json
{
  [...]
  "type": "module",
  "main": "./dist/index.js",
  "module": "./dist/es/index.js",
  "types": "./typings/react-dropzone.d.ts",
  "exports": {
    ".": {
      "import": "./dist/es/index.js",
      "require": "./dist/index.js"
    }
  },
  [...]
}
```

**Comment by cdauth** [comment]
> I don't think you should have to rename to .mjs, you should be able to just specify different export types in package.json

This will not work in a Node.js environment. See https://nodejs.org/api/packages.html#determining-module-system.

**Comment by jacobclarke92** [comment]
@cdauth I agree .mjs is more clear but read the second point in that link - it can be .js when coupled with `"type": "module"` in package.json which I had included in my suggestion.   

I'm by no means a veteran at this stuff though and I don't know the full implications of setting type:module but so far the above approach has worked for me with modules i've made that get consumed by node and bundled via commonjs (also being used in both frontend/backend parts of a Next app).  

Honestly keen to hear more insight on the topic though because it really is confounding stuff..

**Comment by cdauth** [comment]
@jacobclarke92 It's true that `.js` will work if `"type": "module"` is set. However it comes with the following implications:
* All `.js` files in the project will be interpreted as ESM. This means that everything that runs under Node.js (which in this case is probably just the build process) will have to work with ESM, including the build dependencies. This usually requires a bit of work to get it running.
* The CommonJS bundle in `dist/index.js` will also be interpreted as ESM, so it has to be renamed to `dist/index.cjs`. This could be interpreted as a breaking change, requiring a new major release.

I think/hope the future will be all ESM, so `"type": "module"` will be standard practice and only an ESM bundle will be published. More and more projects are making this step, and I think it is a good decision for a major release. Until then, the way to support ESM setups without breaking any existing setups seems to be to add a additional `.mjs` ESM bundle (in addition to the existing `.js` ESM bundle, since some build tools don't support the `.mjs` extension yet).

**Comment by jacobclarke92** [comment]
@cdauth That's some really good, concise info. Thanks!  
Don't know how I've not run into that issue of trying to use packages marked as type:module as CJS yet.. actually looks like next has been preferring MJS since version 12 now, I didn't realise - my project must have never even been importing CJS versions at all .. doh.

Hope I've not derailed this issue too much haha.. I'll show myself out now.  
Still want to add a +1 to this issue and the suggestions you've made though!

**Comment by jacobclarke92** [comment]
Here's a patch-package snippet in the meantime in case it helps others. 

`react-dropzone+14.2.3.patch`
```patch
diff --git a/node_modules/react-dropzone/dist/es/index.js b/node_modules/react-dropzone/dist/es/index.mjs
similarity index 99%
rename from node_modules/react-dropzone/dist/es/index.js
rename to node_modules/react-dropzone/dist/es/index.mjs
index 39d9345..5deaac3 100755
--- a/node_modules/react-dropzone/dist/es/index.js
+++ b/node_modules/react-dropzone/dist/es/index.mjs
@@ -37,7 +37,7 @@ function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) r
 import React, { forwardRef, Fragment, useCallback, useEffect, useImperativeHandle, useMemo, useReducer, useRef } from "react";
 import PropTypes from "prop-types";
 import { fromEvent } from "file-selector";
-import { acceptPropAsAcceptAttr, allFilesAccepted, composeEventHandlers, fileAccepted, fileMatchSize, canUseFileSystemAccessAPI, isAbort, isEvtWithFiles, isIeOrEdge, isPropagationStopped, isSecurityError, onDocumentDragOver, pickerOptionsFromAccept, TOO_MANY_FILES_REJECTION } from "./utils/index";
+import { acceptPropAsAcceptAttr, allFilesAccepted, composeEventHandlers, fileAccepted, fileMatchSize, canUseFileSystemAccessAPI, isAbort, isEvtWithFiles, isIeOrEdge, isPropagationStopped, isSecurityError, onDocumentDragOver, pickerOptionsFromAccept, TOO_MANY_FILES_REJECTION } from "./utils/index.mjs";
 /**
  * Convenience wrapper component for the `useDropzone` hook
  *
@@ -383,7 +383,7 @@ var initialState = {
  * @function useDropzone
  *
  * @param {object} props
- * @param {import("./utils").AcceptProp} [props.accept] Set accepted file types.
+ * @param {import("./utils/index.mjs").AcceptProp} [props.accept] Set accepted file types.
  * Checkout https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker types option for more information.
  * Keep in mind that mime type determination is not reliable across platforms. CSV files,
  * for example, are reported as text/plain under macOS but as application/vnd.ms-excel under
@@ -969,4 +969,4 @@ function reducer(state, action) {
 
 function noop() {}
 
-export { ErrorCode } from "./utils";
\ No newline at end of file
+export { ErrorCode } from "./utils/index.mjs";
\ No newline at end of file
diff --git a/node_modules/react-dropzone/dist/es/utils/index.js b/node_modules/react-dropzone/dist/es/utils/index.mjs
similarity index 99%
rename from node_modules/react-dropzone/dist/es/utils/index.js
rename to node_modules/react-dropzone/dist/es/utils/index.mjs
index 8e5abd5..f155743 100644
--- a/node_modules/react-dropzone/dist/es/utils/index.js
+++ b/node_modules/react-dropzone/dist/es/utils/index.mjs
@@ -26,7 +26,9 @@ function _iterableToArrayLimit(arr, i) { var _i = arr == null ? null : typeof Sy
 
 function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
 
-import accepts from "attr-accept"; // Error codes
+import _accepts from "attr-accept"; // Error codes
+
+const accepts = typeof _accepts === "function" ? _accepts : _accepts.default;
 
 export var FILE_INVALID_TYPE = "file-invalid-type";
 export var FILE_TOO_LARGE = "file-too-large";
diff --git a/node_modules/react-dropzone/package.json b/node_modules/react-dropzone/package.json
index 9409558..97b8175 100644
--- a/node_modules/react-dropzone/package.json
+++ b/node_modules/react-dropzone/package.json
@@ -2,7 +2,13 @@
   "name": "react-dropzone",
   "description": "Simple HTML5 drag-drop zone with React.js",
   "main": "dist/index.js",
-  "module": "dist/es/index.js",
+  "module": "dist/es/index.mjs",
+  "exports": {
+    ".": {
+      "import": "./dist/es/index.mjs",
+      "require": "./dist/index.js"
+    }
+  },
   "sideEffects": false,
   "scripts": {
     "cz": "git-cz",
```

**Comment by micah-redwood** [comment]
Unfortunately still broken as of 14.2.3

**Comment by cblauvelt** [comment]
I was able to use this work around based on a tip from pingdotgg/uploadthing#42.

```ts
import dropzone from "react-dropzone";
const { useDropzone } = dropzone;
```

It appears react-dropzone project hasn't been updated since Oct-2022. Is there anything we can do to help the authors maintain this project? It appears a PR #1293 is available to fix this problem.

**Comment by rtivital** [comment]
Hi everyone, I've created a temporary package [`react-dropzone-esm`](https://www.npmjs.com/package/react-dropzone-esm) which works correctly with modern frameworks.
The package provides both esm and cjs bundles. Exports in package.json are properly configured (you can check the difference between [react-dropzone](https://publint.dev/react-dropzone@14.2.3) and [react-dropzone-esm](https://publint.dev/react-dropzone-esm@15.0.0)).

The package can be used as a drop-in replacement for `react-dropzone` – the source code was not modified, I've changed only the build system.

**Comment by csantos1113** [comment]
Hi all, I am wondering if this project is unmaintained? The solution from @rtivital works fine; but I'm worry that the last commit to this repository was 2 years ago (Oct 12, 2022).

Thanks

**Comment by nexxai** [comment]
> Hi everyone, I've created a temporary package [`react-dropzone-esm`](https://www.npmjs.com/package/react-dropzone-esm) ...

Thank you so much for this.  Have been trying to build an InertiaJS site with SSR and this was causing me headaches.  You saved me a lot of headache!

**Comment by CestDiego** [comment]
I'm still getting this issue in 14.2.6:

```
(node:50197) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
1:57:20 PM [vite] Error when evaluating SSR module /app/routes/pages/user/complete-profile.tsx: failed to import "react-dropzone"
|- /Users/<user>/Documents/Projects/onde-vamos/node_modules/.pnpm/react-dropzone@14.2.6_react@18.3.1/node_modules/react-dropzone/dist/es/index.js:37
import React, { forwardRef, Fragment, useCallback, useEffect, useImperativeHandle, useMemo, useReducer, useRef } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///Users/<user>/Documents/Projects/onde-vamos/node_modules/.pnpm/vite@5.4.7_@types+node@22.5.5_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52998:15)
    at async ssrImport (file:///Users/<user>/Documents/Projects/onde-vamos/node_modules/.pnpm/vite@5.4.7_@types+node@22.5.5_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52856:16)
    at async eval (/Users/<user>/Documents/Projects/onde-vamos/packages/web/app/routes/pages/user/complete-profile.tsx:14:32)
    at async instantiateModule (file:///Users/<user>/Documents/Projects/onde-vamos/node_modules/.pnpm/vite@5.4.7_@types+node@22.5.5_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52914:5)
```

**Comment by rolandjitsu** [comment]
@CestDiego I'm not sure if this is related to this lib. It may be the way you've setup your app. It would be helpful if you shared an example or some way to reproduce the issue.

**Comment by rolandjitsu** [comment]
> Hi everyone, I've created a temporary package [`react-dropzone-esm`](https://www.npmjs.com/package/react-dropzone-esm) which works correctly with modern frameworks. The package provides both esm and cjs bundles. Exports in package.json are properly configured (you can check the difference between [react-dropzone](https://publint.dev/react-dropzone@14.2.3) and [react-dropzone-esm](https://publint.dev/react-dropzone-esm@15.0.0)).
> 
> The package can be used as a drop-in replacement for `react-dropzone` – the source code was not modified, I've changed only the build system.

It would be great if you could make a PR that adds the same support.

**Comment by rtivital** [comment]
> It would be great if you could make a PR that adds the same support.

I've spent some time trying to change only the build tool, but had to:
- rewrite the entire build system to support new formats
- remove some code/parts of the repository as they were incompatible with the new build
- move all dependencies into the same repo as some or all of them had the same esm issue (I do not remember all exact details about other packages)

For everything to work correctly, exports in package.json must look something like this:

```json
  "types": "./types/react-dropzone.d.ts",
  "main": "./dist/cjs/index.js",
  "module": "./dist/esm/index.mjs",
  "exports": {
    ".": {
      "import": {
        "types": "./types/react-dropzone.d.mts",
        "default": "./dist/esm/index.mjs"
      },
      "require": {
        "types": "./types/react-dropzone.d.ts",
        "default": "./dist/cjs/index.js"
      }
    }
  },
```

It is also worth checking publint to verify that everything can be interpreted correctly (currently there are several issues) – https://publint.dev/react-dropzone@14.2.6

You are also welcome to take any part of the source code that I've written for `react-dropzone-esm` package as is or as reference – https://github.com/rtivital/react-dropzone-esm

**Comment by bakikucukcakiroglu** [comment]
I'm still getting this issue in 14.2.9. I started to use `react-dropzone-esm` and it works well.

**Comment by rolandjitsu** [comment]
I think that there are still some issues with the config in package.json.
As pointed out by someone, there are lint errors when using publint.

I will try to look into it next week after I fix my notebook (screen just
got damaged). Unless someone already has a PR to fix that by then.

**Comment by rolandjitsu** [comment]
The previously published fix doesn't solve the issue as far as users report and https://publint.dev/react-dropzone@14.2.9 also shows an error. https://github.com/react-dropzone/react-dropzone/pull/1382 should get rid of the error, but we might need a few more changes still.

**Comment by rolandjitsu** [comment]
There's a patch that should fix the exports error. If anyone tried it and can confirm if there are still issues or not, I'd appreciate it.

**Comment by gjc14** [comment]
Hey I'm using remix with vite. I fix this by adding `ssr.noExternal` in vite.config.ts. I think it just tells vite to bundle with ssr processing.

```ts
export default defineConfig({
    plugins: [
        remix({
            future: {
                v3_fetcherPersist: true,
                v3_relativeSplatPath: true,
                v3_throwAbortReason: true,
                v3_singleFetch: true,
                v3_lazyRouteDiscovery: true,
            },
            routes: async defineRoutes => {
                return flatRoutes(
                    ['routes', ...getPluginRoutes()],
                    defineRoutes
                )
            },
        }),
        tsconfigPaths(),
    ],
    ssr: {
        noExternal: ['lucide-react', 'react-dropzone'],
    },
})
```

**Comment by nateware** [comment]
Lifesaver @gjc14, I'm also using Remix and a google search led me straight here - works great!

**Comment by rolandjitsu** [comment]
https://github.com/react-dropzone/react-dropzone/issues/1319 may also be related to the same issue.

**Comment by bertho-zero** [comment]
@rolandjitsu I still have the issue with the latest version

**Comment by rolandjitsu** [comment]
@bertho-zero we're slowly working towards an fully ESM package.

**Comment by rolandjitsu** [comment]
> have the same problem with latest version of react-dropzone , using with latest version of remix + vite. now using react-dropzone-esm and it's working fine.

Thanks for confirming. I'm glad you found a workaround for now. Hopefully, our ESM compatible version will be out soon if you'd still like to use our lib at that point.

**Comment by austinm911** [comment]
Can confirm this issue using https://github.com/Nic13Gamer/better-upload with Tanstack start using version 14.3.5
