### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by JuanIrache** [react-dropzone/react-dropzone#959]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Fails to compile with error

> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (\node_modules\react\cjs\react.development.js:1465:13)
>     at Object.useRef (\node_modules\react\cjs\react.development.js:1504:20)
>     at F (\node_modules\react-dropzone\src\index.js:384:38)
>     at module.exports../src/renderer/App.js.__webpack_exports__.default (http://localhost:9080/renderer.js:106742:73)
>     at renderWithHooks (http://localhost:9080/renderer.js:86143:18)
>     at mountIndeterminateComponent (http://localhost:9080/renderer.js:88822:13)
>     at beginWork (http://localhost:9080/renderer.js:89936:16)
>     at HTMLUnknownElement.callCallback (http://localhost:9080/renderer.js:71528:14)
>     at Object.invokeGuardedCallbackDev (http://localhost:9080/renderer.js:71577:16)
>     at invokeGuardedCallback (http://localhost:9080/renderer.js:71632:31)

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
> git clone git@github.com:JuanIrache/dropzone-test.git

2.
> npm install

3.
> npm start

**What is the expected behavior?**
A successful compiled app.

Here's the react-dropzone component
https://github.com/JuanIrache/dropzone-test/blob/master/src/renderer/App.js

Using the wrapper component does not solve the issue.

I have no problem using hooks in this setup.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
This happens on Electron (Chromium) + React + Webpack. Version of React and React-dom is 16.13.1. react-dropzone version 10.2.2

There is a previous related issue, but the proposed solutions have no effect https://github.com/react-dropzone/react-dropzone/issues/837

**Comment by JuanIrache** [comment]
Funny finding: If I remove the react-dropzone component and start the daemon with `npm start`, then implement the dropzone with the program still running, it all works perfectly. It's only when I close the program and launch it again that the problem shows up. So the problem seems to arise when starting the server / first compile. The console does not show any relevant differences between good and bad launches, though.

According to [this issue](https://github.com/facebook/react/issues/13991), this might be caused by different react or react-dom versions running in the main app and the module. I have tried forcing react-dropzone to use the same (newer) version of React I'm using. But that didn't solve it.

**Comment by JuanIrache** [comment]
Fixed like https://github.com/facebook/react/issues/13991#issuecomment-611211438
